import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Investment Disclaimer',
  description: 'AlphaWeek is an informational platform. Nothing here constitutes financial advice.',
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-background text-slate-300">
      <header className="border-b border-border">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="font-heading text-xl text-white">AlphaWeek</Link>
          <Link href="/dashboard" className="text-sm text-primary-light hover:underline">Dashboard →</Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-16 space-y-10">
        <div>
          <h1 className="font-heading text-4xl text-white mb-2">Investment Disclaimer</h1>
          <p className="text-muted text-sm">Last updated: May 2026</p>
        </div>

        <div className="p-5 rounded-xl border border-loss/40 bg-loss/5 space-y-2">
          <p className="font-semibold text-red-300 text-base">Not Financial Advice</p>
          <p className="text-sm text-slate-300 leading-relaxed">
            AlphaWeek is an informational and educational platform only. Nothing on this platform — including
            weekly briefs, portfolio analysis, price alerts, watchlist suggestions, or any AI-generated content —
            constitutes financial advice, investment advice, trading advice, or any other type of advice.
          </p>
        </div>

        <section className="space-y-4">
          <h2 className="font-heading text-xl text-white">1. No Investment Advice</h2>
          <p>
            AlphaWeek provides AI-generated summaries, market commentary, and data aggregation as an informational
            service. The content is generated by automated AI systems and is not reviewed by licensed financial
            advisors or investment professionals before delivery. It should not be construed as a recommendation
            to buy, sell, or hold any security, cryptocurrency, or other financial instrument.
          </p>
          <p>
            Always conduct your own research and due diligence before making any investment decision. Consult a
            qualified financial advisor if you require personalised investment advice.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-heading text-xl text-white">2. No Guarantee of Accuracy</h2>
          <p>
            While we make reasonable efforts to source data from reputable providers (Yahoo Finance, NewsAPI,
            Reddit, and others), we make no representations or warranties — express or implied — regarding the
            accuracy, completeness, timeliness, or fitness for purpose of any information provided.
          </p>
          <p>
            Market data, prices, and corporate information can change rapidly. AlphaWeek briefs reflect information
            available at the time of generation and may not reflect the most current market conditions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-heading text-xl text-white">3. Past Performance</h2>
          <p>
            Any references to historical price performance, returns, or market trends are provided for
            informational purposes only. Past performance is not indicative of future results. Investment in
            financial markets involves risk, including the risk of total loss of capital.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-heading text-xl text-white">4. AI-Generated Content Limitations</h2>
          <p>
            AlphaWeek uses large language models to generate investment briefs. AI-generated
            content may contain errors, hallucinations, or outdated information. You should independently verify
            any specific claim, figure, or recommendation before acting on it.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-heading text-xl text-white">5. Regulatory Compliance</h2>
          <p>
            AlphaWeek is not a registered investment advisor, broker-dealer, or financial institution in any
            jurisdiction. AlphaWeek does not hold any financial services licence. Users are responsible for
            complying with the laws and regulations applicable to investment activity in their own jurisdictions.
          </p>
          <p>
            Users in the United States should be aware that AlphaWeek is not registered with the SEC or FINRA.
            Users in India should note that AlphaWeek is not registered with SEBI. No content on this platform
            should be interpreted as SEBI research analyst output.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-heading text-xl text-white">6. Risk Warning</h2>
          <p>
            Investing in stocks, bonds, cryptocurrencies, derivatives, or other financial instruments carries
            significant risk. You may lose some or all of your invested capital. Cryptocurrency markets are
            particularly volatile and unregulated in many jurisdictions. Indian market investments may be affected
            by currency risk, political risk, and regulatory changes.
          </p>
          <p className="font-medium text-slate-200">
            Never invest money you cannot afford to lose.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-heading text-xl text-white">7. Third-Party Links and Data</h2>
          <p>
            AlphaWeek may reference or link to third-party websites, news articles, or data sources. We are not
            responsible for the content, accuracy, or privacy practices of third-party sites. Links do not
            constitute endorsement.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-heading text-xl text-white">8. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by applicable law, AlphaWeek, its officers, directors, employees,
            agents, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or
            punitive damages arising from your use of, or reliance on, any information provided by the Service,
            including but not limited to investment losses.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-heading text-xl text-white">9. Contact</h2>
          <p>
            For questions about this disclaimer, contact us at{' '}
            <a href="mailto:legal@alphaweek.io" className="text-primary-light hover:underline">
              legal@alphaweek.io
            </a>.
          </p>
        </section>

        <div className="border-t border-border pt-8 flex gap-6 text-sm text-muted">
          <Link href="/privacy" className="hover:text-slate-200 transition-colors">Privacy Policy</Link>
          <Link href="/terms" className="hover:text-slate-200 transition-colors">Terms of Service</Link>
          <Link href="/" className="hover:text-slate-200 transition-colors">Home</Link>
        </div>
      </main>
    </div>
  );
}
